spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&useAffectedRows=true&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
